// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package error_reason

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

// 认证相关错误 (401)
// 用户认证相关错误
func IsUserInvalidToken(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == UserErrorReason_USER_INVALID_TOKEN.String() && e.Code == 401
}

// 认证相关错误 (401)
// 用户认证相关错误
func ErrorUserInvalidToken(format string, args ...interface{}) *errors.Error {
	return errors.New(401, UserErrorReason_USER_INVALID_TOKEN.String(), fmt.Sprintf(format, args...))
}

func IsUserTokenExpired(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == UserErrorReason_USER_TOKEN_EXPIRED.String() && e.Code == 401
}

func ErrorUserTokenExpired(format string, args ...interface{}) *errors.Error {
	return errors.New(401, UserErrorReason_USER_TOKEN_EXPIRED.String(), fmt.Sprintf(format, args...))
}

func IsUserInvalidCredentials(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == UserErrorReason_USER_INVALID_CREDENTIALS.String() && e.Code == 401
}

func ErrorUserInvalidCredentials(format string, args ...interface{}) *errors.Error {
	return errors.New(401, UserErrorReason_USER_INVALID_CREDENTIALS.String(), fmt.Sprintf(format, args...))
}

func IsUserRefreshTokenInvalid(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == UserErrorReason_USER_REFRESH_TOKEN_INVALID.String() && e.Code == 401
}

func ErrorUserRefreshTokenInvalid(format string, args ...interface{}) *errors.Error {
	return errors.New(401, UserErrorReason_USER_REFRESH_TOKEN_INVALID.String(), fmt.Sprintf(format, args...))
}

// 请求错误 (400)
// 用户输入相关错误
func IsUserInvalidEmail(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == UserErrorReason_USER_INVALID_EMAIL.String() && e.Code == 400
}

// 请求错误 (400)
// 用户输入相关错误
func ErrorUserInvalidEmail(format string, args ...interface{}) *errors.Error {
	return errors.New(400, UserErrorReason_USER_INVALID_EMAIL.String(), fmt.Sprintf(format, args...))
}

func IsUserInvalidVerificationCode(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == UserErrorReason_USER_INVALID_VERIFICATION_CODE.String() && e.Code == 400
}

func ErrorUserInvalidVerificationCode(format string, args ...interface{}) *errors.Error {
	return errors.New(400, UserErrorReason_USER_INVALID_VERIFICATION_CODE.String(), fmt.Sprintf(format, args...))
}

func IsUserVerificationCodeExpired(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == UserErrorReason_USER_VERIFICATION_CODE_EXPIRED.String() && e.Code == 400
}

func ErrorUserVerificationCodeExpired(format string, args ...interface{}) *errors.Error {
	return errors.New(400, UserErrorReason_USER_VERIFICATION_CODE_EXPIRED.String(), fmt.Sprintf(format, args...))
}

func IsUserInvalidRequest(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == UserErrorReason_USER_INVALID_REQUEST.String() && e.Code == 400
}

func ErrorUserInvalidRequest(format string, args ...interface{}) *errors.Error {
	return errors.New(400, UserErrorReason_USER_INVALID_REQUEST.String(), fmt.Sprintf(format, args...))
}

func IsUserInvalidNickname(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == UserErrorReason_USER_INVALID_NICKNAME.String() && e.Code == 400
}

func ErrorUserInvalidNickname(format string, args ...interface{}) *errors.Error {
	return errors.New(400, UserErrorReason_USER_INVALID_NICKNAME.String(), fmt.Sprintf(format, args...))
}

// 资源冲突 (409)
// 用户资源冲突错误
func IsUserEmailAlreadyExists(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == UserErrorReason_USER_EMAIL_ALREADY_EXISTS.String() && e.Code == 409
}

// 资源冲突 (409)
// 用户资源冲突错误
func ErrorUserEmailAlreadyExists(format string, args ...interface{}) *errors.Error {
	return errors.New(409, UserErrorReason_USER_EMAIL_ALREADY_EXISTS.String(), fmt.Sprintf(format, args...))
}

func IsUserNicknameAlreadyExists(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == UserErrorReason_USER_NICKNAME_ALREADY_EXISTS.String() && e.Code == 409
}

func ErrorUserNicknameAlreadyExists(format string, args ...interface{}) *errors.Error {
	return errors.New(409, UserErrorReason_USER_NICKNAME_ALREADY_EXISTS.String(), fmt.Sprintf(format, args...))
}

// 资源不存在 (404)
// 用户资源不存在错误
func IsUserNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == UserErrorReason_USER_NOT_FOUND.String() && e.Code == 404
}

// 资源不存在 (404)
// 用户资源不存在错误
func ErrorUserNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, UserErrorReason_USER_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsUserProfileNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == UserErrorReason_USER_PROFILE_NOT_FOUND.String() && e.Code == 404
}

func ErrorUserProfileNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, UserErrorReason_USER_PROFILE_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

// 请求过多 (429)
// 用户频率限制错误
func IsUserTooManyRequests(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == UserErrorReason_USER_TOO_MANY_REQUESTS.String() && e.Code == 429
}

// 请求过多 (429)
// 用户频率限制错误
func ErrorUserTooManyRequests(format string, args ...interface{}) *errors.Error {
	return errors.New(429, UserErrorReason_USER_TOO_MANY_REQUESTS.String(), fmt.Sprintf(format, args...))
}

func IsUserLoginTooMany(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == UserErrorReason_USER_LOGIN_TOO_MANY.String() && e.Code == 429
}

func ErrorUserLoginTooMany(format string, args ...interface{}) *errors.Error {
	return errors.New(429, UserErrorReason_USER_LOGIN_TOO_MANY.String(), fmt.Sprintf(format, args...))
}

// 系统错误 (500)
// 用户服务内部错误
func IsUserDatabaseError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == UserErrorReason_USER_DATABASE_ERROR.String() && e.Code == 500
}

// 系统错误 (500)
// 用户服务内部错误
func ErrorUserDatabaseError(format string, args ...interface{}) *errors.Error {
	return errors.New(500, UserErrorReason_USER_DATABASE_ERROR.String(), fmt.Sprintf(format, args...))
}

func IsUserInternalError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == UserErrorReason_USER_INTERNAL_ERROR.String() && e.Code == 500
}

func ErrorUserInternalError(format string, args ...interface{}) *errors.Error {
	return errors.New(500, UserErrorReason_USER_INTERNAL_ERROR.String(), fmt.Sprintf(format, args...))
}

func IsUserServiceUnavailable(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == UserErrorReason_USER_SERVICE_UNAVAILABLE.String() && e.Code == 503
}

func ErrorUserServiceUnavailable(format string, args ...interface{}) *errors.Error {
	return errors.New(503, UserErrorReason_USER_SERVICE_UNAVAILABLE.String(), fmt.Sprintf(format, args...))
}

// 认证相关错误 (401)
func IsAuthInvalidCredentials(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == AuthErrorReason_AUTH_INVALID_CREDENTIALS.String() && e.Code == 401
}

// 认证相关错误 (401)
func ErrorAuthInvalidCredentials(format string, args ...interface{}) *errors.Error {
	return errors.New(401, AuthErrorReason_AUTH_INVALID_CREDENTIALS.String(), fmt.Sprintf(format, args...))
}

func IsAuthTokenInvalid(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == AuthErrorReason_AUTH_TOKEN_INVALID.String() && e.Code == 401
}

func ErrorAuthTokenInvalid(format string, args ...interface{}) *errors.Error {
	return errors.New(401, AuthErrorReason_AUTH_TOKEN_INVALID.String(), fmt.Sprintf(format, args...))
}

func IsAuthTokenExpired(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == AuthErrorReason_AUTH_TOKEN_EXPIRED.String() && e.Code == 401
}

func ErrorAuthTokenExpired(format string, args ...interface{}) *errors.Error {
	return errors.New(401, AuthErrorReason_AUTH_TOKEN_EXPIRED.String(), fmt.Sprintf(format, args...))
}

func IsAuthRefreshTokenInvalid(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == AuthErrorReason_AUTH_REFRESH_TOKEN_INVALID.String() && e.Code == 401
}

func ErrorAuthRefreshTokenInvalid(format string, args ...interface{}) *errors.Error {
	return errors.New(401, AuthErrorReason_AUTH_REFRESH_TOKEN_INVALID.String(), fmt.Sprintf(format, args...))
}

// 请求错误 (400)
func IsAuthInvalidRequest(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == AuthErrorReason_AUTH_INVALID_REQUEST.String() && e.Code == 400
}

// 请求错误 (400)
func ErrorAuthInvalidRequest(format string, args ...interface{}) *errors.Error {
	return errors.New(400, AuthErrorReason_AUTH_INVALID_REQUEST.String(), fmt.Sprintf(format, args...))
}

func IsAuthInvalidEmail(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == AuthErrorReason_AUTH_INVALID_EMAIL.String() && e.Code == 400
}

func ErrorAuthInvalidEmail(format string, args ...interface{}) *errors.Error {
	return errors.New(400, AuthErrorReason_AUTH_INVALID_EMAIL.String(), fmt.Sprintf(format, args...))
}

func IsAuthInvalidCode(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == AuthErrorReason_AUTH_INVALID_CODE.String() && e.Code == 400
}

func ErrorAuthInvalidCode(format string, args ...interface{}) *errors.Error {
	return errors.New(400, AuthErrorReason_AUTH_INVALID_CODE.String(), fmt.Sprintf(format, args...))
}

// 资源冲突 (409)
func IsAuthEmailExists(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == AuthErrorReason_AUTH_EMAIL_EXISTS.String() && e.Code == 409
}

// 资源冲突 (409)
func ErrorAuthEmailExists(format string, args ...interface{}) *errors.Error {
	return errors.New(409, AuthErrorReason_AUTH_EMAIL_EXISTS.String(), fmt.Sprintf(format, args...))
}

// 请求过多 (429)
func IsAuthTooManyRequests(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == AuthErrorReason_AUTH_TOO_MANY_REQUESTS.String() && e.Code == 429
}

// 请求过多 (429)
func ErrorAuthTooManyRequests(format string, args ...interface{}) *errors.Error {
	return errors.New(429, AuthErrorReason_AUTH_TOO_MANY_REQUESTS.String(), fmt.Sprintf(format, args...))
}

func IsAuthLoginBlocked(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == AuthErrorReason_AUTH_LOGIN_BLOCKED.String() && e.Code == 429
}

func ErrorAuthLoginBlocked(format string, args ...interface{}) *errors.Error {
	return errors.New(429, AuthErrorReason_AUTH_LOGIN_BLOCKED.String(), fmt.Sprintf(format, args...))
}

// 系统错误 (500)
func IsAuthDatabaseError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == AuthErrorReason_AUTH_DATABASE_ERROR.String() && e.Code == 500
}

// 系统错误 (500)
func ErrorAuthDatabaseError(format string, args ...interface{}) *errors.Error {
	return errors.New(500, AuthErrorReason_AUTH_DATABASE_ERROR.String(), fmt.Sprintf(format, args...))
}

func IsAuthServiceError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == AuthErrorReason_AUTH_SERVICE_ERROR.String() && e.Code == 500
}

func ErrorAuthServiceError(format string, args ...interface{}) *errors.Error {
	return errors.New(500, AuthErrorReason_AUTH_SERVICE_ERROR.String(), fmt.Sprintf(format, args...))
}

func IsAuthServiceUnavailable(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == AuthErrorReason_AUTH_SERVICE_UNAVAILABLE.String() && e.Code == 503
}

func ErrorAuthServiceUnavailable(format string, args ...interface{}) *errors.Error {
	return errors.New(503, AuthErrorReason_AUTH_SERVICE_UNAVAILABLE.String(), fmt.Sprintf(format, args...))
}

// 数据库错误
func IsDatabaseConnectionError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == SystemErrorReason_DATABASE_CONNECTION_ERROR.String() && e.Code == 500
}

// 数据库错误
func ErrorDatabaseConnectionError(format string, args ...interface{}) *errors.Error {
	return errors.New(500, SystemErrorReason_DATABASE_CONNECTION_ERROR.String(), fmt.Sprintf(format, args...))
}

func IsDatabaseOperationError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == SystemErrorReason_DATABASE_OPERATION_ERROR.String() && e.Code == 500
}

func ErrorDatabaseOperationError(format string, args ...interface{}) *errors.Error {
	return errors.New(500, SystemErrorReason_DATABASE_OPERATION_ERROR.String(), fmt.Sprintf(format, args...))
}

func IsDatabaseTimeoutError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == SystemErrorReason_DATABASE_TIMEOUT_ERROR.String() && e.Code == 500
}

func ErrorDatabaseTimeoutError(format string, args ...interface{}) *errors.Error {
	return errors.New(500, SystemErrorReason_DATABASE_TIMEOUT_ERROR.String(), fmt.Sprintf(format, args...))
}

// 服务错误
func IsServiceUnavailable(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == SystemErrorReason_SERVICE_UNAVAILABLE.String() && e.Code == 503
}

// 服务错误
func ErrorServiceUnavailable(format string, args ...interface{}) *errors.Error {
	return errors.New(503, SystemErrorReason_SERVICE_UNAVAILABLE.String(), fmt.Sprintf(format, args...))
}

func IsServiceOverloaded(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == SystemErrorReason_SERVICE_OVERLOADED.String() && e.Code == 503
}

func ErrorServiceOverloaded(format string, args ...interface{}) *errors.Error {
	return errors.New(503, SystemErrorReason_SERVICE_OVERLOADED.String(), fmt.Sprintf(format, args...))
}

// 基础设施错误
func IsRedisConnectionError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == SystemErrorReason_REDIS_CONNECTION_ERROR.String() && e.Code == 500
}

// 基础设施错误
func ErrorRedisConnectionError(format string, args ...interface{}) *errors.Error {
	return errors.New(500, SystemErrorReason_REDIS_CONNECTION_ERROR.String(), fmt.Sprintf(format, args...))
}

func IsExternalServiceError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == SystemErrorReason_EXTERNAL_SERVICE_ERROR.String() && e.Code == 502
}

func ErrorExternalServiceError(format string, args ...interface{}) *errors.Error {
	return errors.New(502, SystemErrorReason_EXTERNAL_SERVICE_ERROR.String(), fmt.Sprintf(format, args...))
}
