// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: error_reason/error_reason.proto

package v1

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UserService错误定义
type UserErrorReason int32

const (
	// 认证相关错误 (401)
	// 用户认证相关错误
	UserErrorReason_USER_INVALID_TOKEN         UserErrorReason = 0
	UserErrorReason_USER_TOKEN_EXPIRED         UserErrorReason = 1
	UserErrorReason_USER_INVALID_CREDENTIALS   UserErrorReason = 2
	UserErrorReason_USER_REFRESH_TOKEN_INVALID UserErrorReason = 3
	// 请求错误 (400)
	// 用户输入相关错误
	UserErrorReason_USER_INVALID_EMAIL             UserErrorReason = 4
	UserErrorReason_USER_INVALID_VERIFICATION_CODE UserErrorReason = 5
	UserErrorReason_USER_VERIFICATION_CODE_EXPIRED UserErrorReason = 6
	UserErrorReason_USER_INVALID_REQUEST           UserErrorReason = 7
	UserErrorReason_USER_INVALID_NICKNAME          UserErrorReason = 8
	// 资源冲突 (409)
	// 用户资源冲突错误
	UserErrorReason_USER_EMAIL_ALREADY_EXISTS    UserErrorReason = 9
	UserErrorReason_USER_NICKNAME_ALREADY_EXISTS UserErrorReason = 10
	// 资源不存在 (404)
	// 用户资源不存在错误
	UserErrorReason_USER_NOT_FOUND         UserErrorReason = 11
	UserErrorReason_USER_PROFILE_NOT_FOUND UserErrorReason = 12
	// 请求过多 (429)
	// 用户频率限制错误
	UserErrorReason_USER_TOO_MANY_REQUESTS UserErrorReason = 13
	UserErrorReason_USER_LOGIN_TOO_MANY    UserErrorReason = 14
	// 系统错误 (500)
	// 用户服务内部错误
	UserErrorReason_USER_DATABASE_ERROR      UserErrorReason = 15
	UserErrorReason_USER_INTERNAL_ERROR      UserErrorReason = 16
	UserErrorReason_USER_SERVICE_UNAVAILABLE UserErrorReason = 17
)

// Enum value maps for UserErrorReason.
var (
	UserErrorReason_name = map[int32]string{
		0:  "USER_INVALID_TOKEN",
		1:  "USER_TOKEN_EXPIRED",
		2:  "USER_INVALID_CREDENTIALS",
		3:  "USER_REFRESH_TOKEN_INVALID",
		4:  "USER_INVALID_EMAIL",
		5:  "USER_INVALID_VERIFICATION_CODE",
		6:  "USER_VERIFICATION_CODE_EXPIRED",
		7:  "USER_INVALID_REQUEST",
		8:  "USER_INVALID_NICKNAME",
		9:  "USER_EMAIL_ALREADY_EXISTS",
		10: "USER_NICKNAME_ALREADY_EXISTS",
		11: "USER_NOT_FOUND",
		12: "USER_PROFILE_NOT_FOUND",
		13: "USER_TOO_MANY_REQUESTS",
		14: "USER_LOGIN_TOO_MANY",
		15: "USER_DATABASE_ERROR",
		16: "USER_INTERNAL_ERROR",
		17: "USER_SERVICE_UNAVAILABLE",
	}
	UserErrorReason_value = map[string]int32{
		"USER_INVALID_TOKEN":             0,
		"USER_TOKEN_EXPIRED":             1,
		"USER_INVALID_CREDENTIALS":       2,
		"USER_REFRESH_TOKEN_INVALID":     3,
		"USER_INVALID_EMAIL":             4,
		"USER_INVALID_VERIFICATION_CODE": 5,
		"USER_VERIFICATION_CODE_EXPIRED": 6,
		"USER_INVALID_REQUEST":           7,
		"USER_INVALID_NICKNAME":          8,
		"USER_EMAIL_ALREADY_EXISTS":      9,
		"USER_NICKNAME_ALREADY_EXISTS":   10,
		"USER_NOT_FOUND":                 11,
		"USER_PROFILE_NOT_FOUND":         12,
		"USER_TOO_MANY_REQUESTS":         13,
		"USER_LOGIN_TOO_MANY":            14,
		"USER_DATABASE_ERROR":            15,
		"USER_INTERNAL_ERROR":            16,
		"USER_SERVICE_UNAVAILABLE":       17,
	}
)

func (x UserErrorReason) Enum() *UserErrorReason {
	p := new(UserErrorReason)
	*p = x
	return p
}

func (x UserErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_error_reason_error_reason_proto_enumTypes[0].Descriptor()
}

func (UserErrorReason) Type() protoreflect.EnumType {
	return &file_error_reason_error_reason_proto_enumTypes[0]
}

func (x UserErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserErrorReason.Descriptor instead.
func (UserErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_error_reason_error_reason_proto_rawDescGZIP(), []int{0}
}

// AuthService错误定义
type AuthErrorReason int32

const (
	// 认证相关错误 (401)
	AuthErrorReason_AUTH_INVALID_CREDENTIALS   AuthErrorReason = 0
	AuthErrorReason_AUTH_TOKEN_INVALID         AuthErrorReason = 1
	AuthErrorReason_AUTH_TOKEN_EXPIRED         AuthErrorReason = 2
	AuthErrorReason_AUTH_REFRESH_TOKEN_INVALID AuthErrorReason = 3
	// 请求错误 (400)
	AuthErrorReason_AUTH_INVALID_REQUEST AuthErrorReason = 4
	AuthErrorReason_AUTH_INVALID_EMAIL   AuthErrorReason = 5
	AuthErrorReason_AUTH_INVALID_CODE    AuthErrorReason = 6
	// 资源冲突 (409)
	AuthErrorReason_AUTH_EMAIL_EXISTS AuthErrorReason = 7
	// 请求过多 (429)
	AuthErrorReason_AUTH_TOO_MANY_REQUESTS AuthErrorReason = 8
	AuthErrorReason_AUTH_LOGIN_BLOCKED     AuthErrorReason = 9
	// 系统错误 (500)
	AuthErrorReason_AUTH_DATABASE_ERROR      AuthErrorReason = 10
	AuthErrorReason_AUTH_SERVICE_ERROR       AuthErrorReason = 11
	AuthErrorReason_AUTH_SERVICE_UNAVAILABLE AuthErrorReason = 12
)

// Enum value maps for AuthErrorReason.
var (
	AuthErrorReason_name = map[int32]string{
		0:  "AUTH_INVALID_CREDENTIALS",
		1:  "AUTH_TOKEN_INVALID",
		2:  "AUTH_TOKEN_EXPIRED",
		3:  "AUTH_REFRESH_TOKEN_INVALID",
		4:  "AUTH_INVALID_REQUEST",
		5:  "AUTH_INVALID_EMAIL",
		6:  "AUTH_INVALID_CODE",
		7:  "AUTH_EMAIL_EXISTS",
		8:  "AUTH_TOO_MANY_REQUESTS",
		9:  "AUTH_LOGIN_BLOCKED",
		10: "AUTH_DATABASE_ERROR",
		11: "AUTH_SERVICE_ERROR",
		12: "AUTH_SERVICE_UNAVAILABLE",
	}
	AuthErrorReason_value = map[string]int32{
		"AUTH_INVALID_CREDENTIALS":   0,
		"AUTH_TOKEN_INVALID":         1,
		"AUTH_TOKEN_EXPIRED":         2,
		"AUTH_REFRESH_TOKEN_INVALID": 3,
		"AUTH_INVALID_REQUEST":       4,
		"AUTH_INVALID_EMAIL":         5,
		"AUTH_INVALID_CODE":          6,
		"AUTH_EMAIL_EXISTS":          7,
		"AUTH_TOO_MANY_REQUESTS":     8,
		"AUTH_LOGIN_BLOCKED":         9,
		"AUTH_DATABASE_ERROR":        10,
		"AUTH_SERVICE_ERROR":         11,
		"AUTH_SERVICE_UNAVAILABLE":   12,
	}
)

func (x AuthErrorReason) Enum() *AuthErrorReason {
	p := new(AuthErrorReason)
	*p = x
	return p
}

func (x AuthErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_error_reason_error_reason_proto_enumTypes[1].Descriptor()
}

func (AuthErrorReason) Type() protoreflect.EnumType {
	return &file_error_reason_error_reason_proto_enumTypes[1]
}

func (x AuthErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthErrorReason.Descriptor instead.
func (AuthErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_error_reason_error_reason_proto_rawDescGZIP(), []int{1}
}

// 系统级错误定义
type SystemErrorReason int32

const (
	// 数据库错误
	SystemErrorReason_DATABASE_CONNECTION_ERROR SystemErrorReason = 0
	SystemErrorReason_DATABASE_OPERATION_ERROR  SystemErrorReason = 1
	SystemErrorReason_DATABASE_TIMEOUT_ERROR    SystemErrorReason = 2
	// 服务错误
	SystemErrorReason_SERVICE_UNAVAILABLE SystemErrorReason = 3
	SystemErrorReason_SERVICE_OVERLOADED  SystemErrorReason = 4
	// 基础设施错误
	SystemErrorReason_REDIS_CONNECTION_ERROR SystemErrorReason = 5
	SystemErrorReason_EXTERNAL_SERVICE_ERROR SystemErrorReason = 6
)

// Enum value maps for SystemErrorReason.
var (
	SystemErrorReason_name = map[int32]string{
		0: "DATABASE_CONNECTION_ERROR",
		1: "DATABASE_OPERATION_ERROR",
		2: "DATABASE_TIMEOUT_ERROR",
		3: "SERVICE_UNAVAILABLE",
		4: "SERVICE_OVERLOADED",
		5: "REDIS_CONNECTION_ERROR",
		6: "EXTERNAL_SERVICE_ERROR",
	}
	SystemErrorReason_value = map[string]int32{
		"DATABASE_CONNECTION_ERROR": 0,
		"DATABASE_OPERATION_ERROR":  1,
		"DATABASE_TIMEOUT_ERROR":    2,
		"SERVICE_UNAVAILABLE":       3,
		"SERVICE_OVERLOADED":        4,
		"REDIS_CONNECTION_ERROR":    5,
		"EXTERNAL_SERVICE_ERROR":    6,
	}
)

func (x SystemErrorReason) Enum() *SystemErrorReason {
	p := new(SystemErrorReason)
	*p = x
	return p
}

func (x SystemErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SystemErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_error_reason_error_reason_proto_enumTypes[2].Descriptor()
}

func (SystemErrorReason) Type() protoreflect.EnumType {
	return &file_error_reason_error_reason_proto_enumTypes[2]
}

func (x SystemErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SystemErrorReason.Descriptor instead.
func (SystemErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_error_reason_error_reason_proto_rawDescGZIP(), []int{2}
}

var File_error_reason_error_reason_proto protoreflect.FileDescriptor

const file_error_reason_error_reason_proto_rawDesc = "" +
	"\n" +
	"\x1ferror_reason/error_reason.proto\x12\auser.v1\x1a\x13errors/errors.proto*\xfc\x04\n" +
	"\x0fUserErrorReason\x12\x1c\n" +
	"\x12USER_INVALID_TOKEN\x10\x00\x1a\x04\xa8E\x91\x03\x12\x1c\n" +
	"\x12USER_TOKEN_EXPIRED\x10\x01\x1a\x04\xa8E\x91\x03\x12\"\n" +
	"\x18USER_INVALID_CREDENTIALS\x10\x02\x1a\x04\xa8E\x91\x03\x12$\n" +
	"\x1aUSER_REFRESH_TOKEN_INVALID\x10\x03\x1a\x04\xa8E\x91\x03\x12\x1c\n" +
	"\x12USER_INVALID_EMAIL\x10\x04\x1a\x04\xa8E\x90\x03\x12(\n" +
	"\x1eUSER_INVALID_VERIFICATION_CODE\x10\x05\x1a\x04\xa8E\x90\x03\x12(\n" +
	"\x1eUSER_VERIFICATION_CODE_EXPIRED\x10\x06\x1a\x04\xa8E\x90\x03\x12\x1e\n" +
	"\x14USER_INVALID_REQUEST\x10\a\x1a\x04\xa8E\x90\x03\x12\x1f\n" +
	"\x15USER_INVALID_NICKNAME\x10\b\x1a\x04\xa8E\x90\x03\x12#\n" +
	"\x19USER_EMAIL_ALREADY_EXISTS\x10\t\x1a\x04\xa8E\x99\x03\x12&\n" +
	"\x1cUSER_NICKNAME_ALREADY_EXISTS\x10\n" +
	"\x1a\x04\xa8E\x99\x03\x12\x18\n" +
	"\x0eUSER_NOT_FOUND\x10\v\x1a\x04\xa8E\x94\x03\x12 \n" +
	"\x16USER_PROFILE_NOT_FOUND\x10\f\x1a\x04\xa8E\x94\x03\x12 \n" +
	"\x16USER_TOO_MANY_REQUESTS\x10\r\x1a\x04\xa8E\xad\x03\x12\x1d\n" +
	"\x13USER_LOGIN_TOO_MANY\x10\x0e\x1a\x04\xa8E\xad\x03\x12\x1d\n" +
	"\x13USER_DATABASE_ERROR\x10\x0f\x1a\x04\xa8E\xf4\x03\x12\x1d\n" +
	"\x13USER_INTERNAL_ERROR\x10\x10\x1a\x04\xa8E\xf4\x03\x12\"\n" +
	"\x18USER_SERVICE_UNAVAILABLE\x10\x11\x1a\x04\xa8E\xf7\x03\x1a\x04\xa0E\xf4\x03*\xb6\x03\n" +
	"\x0fAuthErrorReason\x12\"\n" +
	"\x18AUTH_INVALID_CREDENTIALS\x10\x00\x1a\x04\xa8E\x91\x03\x12\x1c\n" +
	"\x12AUTH_TOKEN_INVALID\x10\x01\x1a\x04\xa8E\x91\x03\x12\x1c\n" +
	"\x12AUTH_TOKEN_EXPIRED\x10\x02\x1a\x04\xa8E\x91\x03\x12$\n" +
	"\x1aAUTH_REFRESH_TOKEN_INVALID\x10\x03\x1a\x04\xa8E\x91\x03\x12\x1e\n" +
	"\x14AUTH_INVALID_REQUEST\x10\x04\x1a\x04\xa8E\x90\x03\x12\x1c\n" +
	"\x12AUTH_INVALID_EMAIL\x10\x05\x1a\x04\xa8E\x90\x03\x12\x1b\n" +
	"\x11AUTH_INVALID_CODE\x10\x06\x1a\x04\xa8E\x90\x03\x12\x1b\n" +
	"\x11AUTH_EMAIL_EXISTS\x10\a\x1a\x04\xa8E\x99\x03\x12 \n" +
	"\x16AUTH_TOO_MANY_REQUESTS\x10\b\x1a\x04\xa8E\xad\x03\x12\x1c\n" +
	"\x12AUTH_LOGIN_BLOCKED\x10\t\x1a\x04\xa8E\xad\x03\x12\x1d\n" +
	"\x13AUTH_DATABASE_ERROR\x10\n" +
	"\x1a\x04\xa8E\xf4\x03\x12\x1c\n" +
	"\x12AUTH_SERVICE_ERROR\x10\v\x1a\x04\xa8E\xf4\x03\x12\"\n" +
	"\x18AUTH_SERVICE_UNAVAILABLE\x10\f\x1a\x04\xa8E\xf7\x03\x1a\x04\xa0E\xf4\x03*\x85\x02\n" +
	"\x11SystemErrorReason\x12#\n" +
	"\x19DATABASE_CONNECTION_ERROR\x10\x00\x1a\x04\xa8E\xf4\x03\x12\"\n" +
	"\x18DATABASE_OPERATION_ERROR\x10\x01\x1a\x04\xa8E\xf4\x03\x12 \n" +
	"\x16DATABASE_TIMEOUT_ERROR\x10\x02\x1a\x04\xa8E\xf4\x03\x12\x1d\n" +
	"\x13SERVICE_UNAVAILABLE\x10\x03\x1a\x04\xa8E\xf7\x03\x12\x1c\n" +
	"\x12SERVICE_OVERLOADED\x10\x04\x1a\x04\xa8E\xf7\x03\x12 \n" +
	"\x16REDIS_CONNECTION_ERROR\x10\x05\x1a\x04\xa8E\xf4\x03\x12 \n" +
	"\x16EXTERNAL_SERVICE_ERROR\x10\x06\x1a\x04\xa8E\xf6\x03\x1a\x04\xa0E\xf4\x03B'\n" +
	"\x10user.api.user.v1Z\x13user/api/user/v1;v1b\x06proto3"

var (
	file_error_reason_error_reason_proto_rawDescOnce sync.Once
	file_error_reason_error_reason_proto_rawDescData []byte
)

func file_error_reason_error_reason_proto_rawDescGZIP() []byte {
	file_error_reason_error_reason_proto_rawDescOnce.Do(func() {
		file_error_reason_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_error_reason_error_reason_proto_rawDesc), len(file_error_reason_error_reason_proto_rawDesc)))
	})
	return file_error_reason_error_reason_proto_rawDescData
}

var file_error_reason_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_error_reason_error_reason_proto_goTypes = []any{
	(UserErrorReason)(0),   // 0: user.v1.UserErrorReason
	(AuthErrorReason)(0),   // 1: user.v1.AuthErrorReason
	(SystemErrorReason)(0), // 2: user.v1.SystemErrorReason
}
var file_error_reason_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_error_reason_error_reason_proto_init() }
func file_error_reason_error_reason_proto_init() {
	if File_error_reason_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_error_reason_error_reason_proto_rawDesc), len(file_error_reason_error_reason_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_error_reason_error_reason_proto_goTypes,
		DependencyIndexes: file_error_reason_error_reason_proto_depIdxs,
		EnumInfos:         file_error_reason_error_reason_proto_enumTypes,
	}.Build()
	File_error_reason_error_reason_proto = out.File
	file_error_reason_error_reason_proto_goTypes = nil
	file_error_reason_error_reason_proto_depIdxs = nil
}
