// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"user/internal/biz"
	"user/internal/conf"
	"user/internal/data"
	"user/internal/server"
	"user/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	greeterService := service.NewGreeterService(greeterUsecase)
	authRepository := data.NewAuthRepository(dataData, logger)
	authUsecase := biz.NewAuthUsecase(authRepository, logger)
	db := data.NewDB(dataData)
	userRepository := data.NewUserRepository(db, logger)
	codeRepository := data.NewCodeRepository(dataData, logger)
	userUsecase := biz.NewUserUsecase(userRepository, codeRepository, authRepository, logger)
	authService := service.NewAuthService(authUsecase, userUsecase, logger)
	userService := service.NewUserService(userUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, greeterService, authService, userService, logger)
	httpServer := server.NewHTTPServer(confServer, greeterService, authService, userService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
