// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"user/internal/biz"
	"user/internal/conf"
	"user/internal/data"
	"user/internal/pkg/snowflake"
	"user/internal/server"
	"user/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, email *conf.Email, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	authRepository := data.NewAuthRepository(dataData, logger)
	authUsecase := biz.NewAuthUsecase(authRepository, logger)
	db := data.NewDB(dataData)
	userRepository := data.NewUserRepository(db, logger)
	codeRepository := data.NewCodeRepository(dataData, logger)
	snowflakeConfig := snowflake.DefaultSnowflakeConfig()
	snowflakeGenerator, err := snowflake.NewSnowflakeGenerator(snowflakeConfig, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	emailConfig := biz.NewEmailConfig(email)
	userUsecase := biz.NewUserUsecase(userRepository, codeRepository, authRepository, snowflakeGenerator, emailConfig, logger)
	authService := service.NewAuthService(authUsecase, userUsecase, logger)
	userService := service.NewUserService(userUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, authService, userService, logger)
	httpServer := server.NewHTTPServer(confServer, authService, userService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
